services:

  app1:
    build:
      context: ./app
    image: examenfinal-app:1.0.0
    container_name: examenfinal-app-01
    environment:
      APP_NAME: Examen-Final-App
      APP_VERSION: 1.0.0
      INSTANCE_NAME: app-01
    networks:
      - examenfinal-net
    restart: unless-stopped

  app2:
    build:
      context: ./app
    image: examenfinal-app:1.0.0
    container_name: examenfinal-app-02
    environment:
      APP_NAME: Examen-Final-App
      APP_VERSION: 1.0.0
      INSTANCE_NAME: app-02
    networks:
      - examenfinal-net
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    image: examenfinal-nginx:1.0.0
    container_name: examenfinal-nginx
    ports:
      - "80:80"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    networks:
      - examenfinal-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: examenfinal-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - examenfinal-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: examenfinal-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - examenfinal-net
    restart: unless-stopped

networks:
  examenfinal-net:
    name: examenfinal-net
    driver: bridge

volumes:
  prometheus-data:
    name: devsecops-prometheus-data

  grafana-data:
    name: devsecops-grafana-data